// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJYOqRz-VgzgKKxbdMK5d08vaq9jrgtP8',
    appId: '1:267257828606:web:2a978dec65e8704a2d81af',
    messagingSenderId: '267257828606',
    projectId: 'bd-proyecto-27a5d',
    authDomain: 'bd-proyecto-27a5d.firebaseapp.com',
    storageBucket: 'bd-proyecto-27a5d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKzqw_rFLDSFxU1CtBKQHizZAc2a3FEQg',
    appId: '1:267257828606:android:a7e7b1076b1d39c82d81af',
    messagingSenderId: '267257828606',
    projectId: 'bd-proyecto-27a5d',
    storageBucket: 'bd-proyecto-27a5d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHsr1j38hg1ajJNz_t2a4ztzNxRYrKAbA',
    appId: '1:267257828606:ios:6f1c841bb3899c382d81af',
    messagingSenderId: '267257828606',
    projectId: 'bd-proyecto-27a5d',
    storageBucket: 'bd-proyecto-27a5d.firebasestorage.app',
    iosBundleId: 'com.example.butacaysofa',
  );
}
